project:
  type: website
  output-dir: docs

website:
  title: "Personal Blog"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Blog"
        href: blog.qmd
    right:
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css



